defaults:
  - writer: cometml 
  - datasets@train: asvspoof_train   # возьмёт configs/datasets/asvspoof_train.yaml  → cfg.datasets.train
  - datasets@dev:   asvspoof_dev     # configs/datasets/asvspoof_dev.yaml     → cfg.datasets.dev
  - datasets@eval:  asvspoof_eval    # configs/datasets/asvspoof_eval.yaml    → cfg.datasets.eval
  - _self_

seed: 254

dataloader:
  collate_fn:
    _target_: src.datasets.collate.pad_collate

batch_size: 64
num_workers: 4
shuffle: true
drop_last: true
 
model:
  _target_: src.model.LightCNN9
  dropout_p: 0.35

loss_fn:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4
  weight_decay: 1e-4

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 30

# loss_fn:
#   _target_: torch.nn.CrossEntropyLoss

trainer:
  epochs: 12
  log_steps: 50
  device: cuda 

writer:
  _target_: src.logger.CometMLWriter # ← путь к твоему классу
  project_name: "asvspoof_lcnn"
  workspace: null
  run_name: "run-${now:%Y%m%d_%H%M%S}"
  mode: "online" # или offline
  log_code: false # все kwargs, которые есть в __init__
  log_graph: false
  auto_metric_logging: false
  auto_param_logging: false
