_target_: src.logger.CometMLWriter
project_name: "asvspoof_lcnn"
workspace: null
run_name: "run-${now:%Y%m%d_%H%M%S}"
mode: "online"
log_code: false
log_graph: false
auto_metric_logging: false
auto_param_logging: false
